// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xedge_detect.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XEdge_detect_CfgInitialize(XEdge_detect *InstancePtr, XEdge_detect_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Crtl_bus_BaseAddress = ConfigPtr->Crtl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XEdge_detect_Start(XEdge_detect *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEdge_detect_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XEDGE_DETECT_CRTL_BUS_ADDR_AP_CTRL) & 0x80;
    XEdge_detect_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XEDGE_DETECT_CRTL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XEdge_detect_IsDone(XEdge_detect *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEdge_detect_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XEDGE_DETECT_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XEdge_detect_IsIdle(XEdge_detect *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEdge_detect_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XEDGE_DETECT_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XEdge_detect_IsReady(XEdge_detect *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEdge_detect_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XEDGE_DETECT_CRTL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XEdge_detect_EnableAutoRestart(XEdge_detect *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEdge_detect_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XEDGE_DETECT_CRTL_BUS_ADDR_AP_CTRL, 0x80);
}

void XEdge_detect_DisableAutoRestart(XEdge_detect *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEdge_detect_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XEDGE_DETECT_CRTL_BUS_ADDR_AP_CTRL, 0);
}

void XEdge_detect_InterruptGlobalEnable(XEdge_detect *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEdge_detect_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XEDGE_DETECT_CRTL_BUS_ADDR_GIE, 1);
}

void XEdge_detect_InterruptGlobalDisable(XEdge_detect *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEdge_detect_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XEDGE_DETECT_CRTL_BUS_ADDR_GIE, 0);
}

void XEdge_detect_InterruptEnable(XEdge_detect *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEdge_detect_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XEDGE_DETECT_CRTL_BUS_ADDR_IER);
    XEdge_detect_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XEDGE_DETECT_CRTL_BUS_ADDR_IER, Register | Mask);
}

void XEdge_detect_InterruptDisable(XEdge_detect *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEdge_detect_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XEDGE_DETECT_CRTL_BUS_ADDR_IER);
    XEdge_detect_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XEDGE_DETECT_CRTL_BUS_ADDR_IER, Register & (~Mask));
}

void XEdge_detect_InterruptClear(XEdge_detect *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEdge_detect_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XEDGE_DETECT_CRTL_BUS_ADDR_ISR, Mask);
}

u32 XEdge_detect_InterruptGetEnabled(XEdge_detect *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEdge_detect_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XEDGE_DETECT_CRTL_BUS_ADDR_IER);
}

u32 XEdge_detect_InterruptGetStatus(XEdge_detect *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEdge_detect_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XEDGE_DETECT_CRTL_BUS_ADDR_ISR);
}

